name: Test

on: [push]

jobs:
  example:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Разрешаем запись в репозиторий
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Create file
      run: cat Files/* >  Result.yaml
      
    - name: Commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        if git ls-files --error-unmatch "Result.yaml" >/dev/null 2>&1; then
          git rm -f Result.yaml
        fi
        git add Result.yaml
        git commit -m "Add file"
        git push
