name: Test

on: [push]

jobs:
  example:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Разрешаем запись в репозиторий
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Check for updates
      run: git diff --quiet || { echo "Изменений нет, выходим"; exit 0; }
      
    - name: Create file
      run: cat Files/* >  Result.yaml
      
    - name: Commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -f Result.yaml 
        git commit -m "Add file"
        git push
